# docker-compose.yml
version: '3.5'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:{{es_version}}
    networks:
      - elastic
    ports:
      - "{{es_port}}:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:{{es_version}}
    volumes:
      - type: bind
        source: "{{ es_compose_path }}/logstash-pipeline"
        target: /usr/share/logstash/pipeline
      - type: bind
        source: "{{ es_compose_path }}/logstash.yml"
        target: /usr/share/logstash/config/logstash.yml
    networks:
      - elastic
    ports:
      - "{{logstash_port}}:5044"
#      - "{{logstash_api}}:9600"

  kibana:
    image: docker.elastic.co/kibana/kibana:{{es_version}}
    volumes:
      - type: bind
        source: "{{ es_compose_path }}/kibana.yml"
        target: "/usr/share/kibana/config/kibana.yml"
    networks:
      - elastic
    ports:
      - "{{kibana_port}}:5601"

  grafana:
    image: grafana/grafana
    volumes:
      - type: bind
        source: "{{ es_compose_path }}/grafana-elasticsearch.yml"
        target: /etc/grafana/provisioning/datasources/elasticsearch.yml
    networks:
      - elastic
    ports:
      - "{{grafana_port}}:3000"

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:{{es_version}}
    command: "-system.hostfs=/hostfs"
    user: root
    volumes:
      - type: bind
        source: /proc
        target: /hostfs/proc
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /hostfs/sys/fs/cgroup
        read_only: true
      - type: bind
        source: /
        target: /hostfs
        read_only: true
      - type: bind
        source: "{{ es_compose_path }}/metricbeat.yml"
        target: /usr/share/metricbeat/metricbeat.yml
      - type: bind
        source: "{{ es_compose_path }}/metricbeat-modules.d"
        target: /usr/share/metricbeat/modules.d
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    network_mode: host

  filebeat:
    image: docker.elastic.co/beats/filebeat:{{es_version}}
    user: root
    volumes:
      - type: bind
        source: /var/log
        target: /mnt/log
      - type: bind
        source: "{{ es_compose_path }}/filebeat.yml"
        target: /usr/share/filebeat/filebeat.yml
      - type: bind
        source: "{{ es_compose_path }}/filebeat-modules.d"
        target: /usr/share/filebeat/modules.d
      - type: bind
        source: "{{ es_compose_path }}/filebeat-prospectors.d"
        target: /usr/share/filebeat/prospectors.d

    networks:
      - elastic


networks:
  elastic:
