
{% if es_config %}
{{ es_config | to_nice_yaml }}
{% endif %}

#################################### Paths ####################################

path.data: {{ es_data_dirs | array_to_str }}
path.logs: {{ es_log_dir }}

{% if es_enable_xpack %}
{% if not "security" in es_xpack_features %}
xpack.security.enabled: false
{% endif %}

{% if not "monitoring" in es_xpack_features %}
xpack.monitoring.enabled: false
{% endif %}

{% if not "alerting" in es_xpack_features %}
xpack.watcher.enabled: false
{% endif %}

{% if not "ml" in es_xpack_features %}
xpack.ml.enabled: false
{% endif %}

{% if not "graph" in es_xpack_features %}
xpack.graph.enabled: false
{% endif %}
{% endif %}
