---
apiVersion: 1

datasources:
- name: elasticsearch
  type: elasticsearch
  orgId: 1
  typeLogoUrl: public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg
  access: proxy
  url: http://elasticsearch:{{es_port}}
  password: ''
  user: ''
  database: ''
  basicAuth: false
  isDefault: true
  jsonData:
    esVersion: 5
    keepCookies: []
    maxConcurrentShardRequests: 256
    timeField: "@timestamp"
  readOnly: false
