---
# tasks file for deploy-metricbeat

# https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.4.0-x86_64.rpm

- name: install metricbeat rpm package
  yum:
    name: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{metricbeat_version}}-{{ansible_architecture}}.rpm
    state: present

- name: setup metricbeat config
  copy:
    src: metricbeat.yml
    dest: /etc/metricbeat/metricbeat.yml

- name: start metricbeat and ensure it runs at boot
  service:
    name: metricbeat
    enabled: yes
    state: started

