---
# tasks file for deploy-metricbeat

# https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.4.0-x86_64.rpm

- name: install metricbeat rpm package
  yum:
    name: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{metricbeat_version}}-{{ansible_architecture}}.rpm
    state: present

- name: copy metricbeat modules.d
  copy:
    src: "{{ item }}"
    dest: "{{ metricbeat_etc }}/"
  with_items: "{{ metricbeat_modules }}"
  notify:
    - restart metricbeat

- name: setup metricbeat config
  template:
    src: metricbeat.yml
    dest: /etc/metricbeat/metricbeat.yml
  notify:
    - restart metricbeat

- name: start metricbeat and ensure it runs at boot
  service:
    name: metricbeat
    enabled: yes
    state: started

